### Get player characters
GET http://localhost:25570/v-rising-discord-bot/characters

### Get player activities
GET http://localhost:25570/v-rising-discord-bot/player-activities

### Get pvp kills
GET http://localhost:25570/v-rising-discord-bot/pvp-kills

### Metrics
GET http://localhost:25570/metrics

### Console
GET http://localhost:25570/console/v1?input=sendserverannouncement some message

### Messages
POST http://localhost:25570/api/message/v1
Content-Type: application/json

{
    "message": "the actual message"
}

### Shutdown
POST http://localhost:25570/api/shutdown/v1
Content-Type: application/json

{
    "shutdown": true
}

### Save
POST http://localhost:25570/api/save/v1
Content-Type: application/json

{}

### Discord Webhook
POST https://discord.com/api/webhooks/xxx/xxx
Content-Type: application/json

{
    "username": "Jarvis",
    "avatar_url": "https://raw.githubusercontent.com/DarkAtra/v-rising-discord-bot/main/docs/assets/icon.png",
    "content": "Atra: Test"
}
