[config]
schemaVersion = "0.0.1"

[package]
namespace = "DarkAtra"
name = "VRisingDiscordBotCompanion"
description = "A companion mod for DarkAtra's v-rising-discord-bot."
websiteUrl = "https://github.com/DarkAtra/v-rising-discord-bot-companion"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.733.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./build/v-rising-discord-bot-companion.dll"
target = "v-rising-discord-bot-companion.dll"

[publish]
repository = "https://thunderstore.io"
communities = ["v-rising"]

[publish.categories]
v-rising = ["oakveil-update", "mods", "server"]
